name: flutter_base_master
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.12.0 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.1
  fluttertoast: 8.0.8
  dio: 4.0.4
  lottie: 1.2.1
  connectivity: 3.0.6
  shared_preferences: 2.0.11
  flutter_screenutil: 5.0.1+1
  pull_to_refresh: 2.0.0
  webview_flutter: 3.0.0
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^1.0.0
  lints: 1.0.1
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/lottie/
    - assets/gif/
    - assets/images/
  uses-material-design: true

